### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by ghost** [jczic/BLEAdvReader#1]
Hey

Could you confirm what board you have had this working on before. I am trying to use this on a Pycom SiPy and get the following issue:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
MemoryError: memory allocation failed, allocating 97 bytes
Pycom MicroPython 1.18.2.r7 [v1.8.6-849-df9f237] on 2019-05-14; SiPy with ESP32

I have not made any changes to either the main of the bleAdvReader.py file.

**Comment by jczic** [comment]
Hi,
You don't have enough memory to import many modules if you don't have a 4Mo SDRAM version of the pycom chip or if you don't use the "frozen" directory to put your src and compile the firmware yourself.
However, it's limited to use /flash directly to put all your modules.
Good luck @Smigg92 👍

**Comment by ghost** [comment]
That did the trick.

Thanks for the help :)
