### ISSUE TITLE
tlm temp data

### ISSUE THREAD

**Issue by ghost** [jczic/BLEAdvReader#2]
Hey noticed there is an issue with the decodeing of Eddystone TLM temperature data:

in bleAdvReader.py line 281:
                temp   = unpack('<h', data[4:6])[0]

This is currently giving results like -16360°C, where the result should be 24.75°C.

if we have \x18\xc0\ at data[4:6], data[4] should be parsed for the  whole number and data[5] is parsed for the decimal point. an example would be.

def twos_complement(hexstr, bits):
     value = int(hexstr,16)
     if value & (1 << (bits-1)):
         value -= 1 << bits
     return value

temp1= twos_complement(data[4], 16)
temp2 = twos_complement(data[5], 16) / 256
temp = temp1 + temp2

print(temp)
24.75

**Comment by jczic** [comment]
Hello and thank you !
I've commited a code to reading this fixed point value of temperature :
https://github.com/jczic/BLEAdvReader/commit/2f02d5127187f3e6deac35df93449cb02161837f
That's correct for you ?

**Comment by ghost** [comment]
Hey,

Awesome work. Issue is fixed and works great
