### ISSUE TITLE
 input data 

### ISSUE THREAD

**Issue by surajrimal** [jczic/BLEAdvReader#3]
What type of input data is expected by this program

**Comment by jczic** [comment]
Hello,
You can check : 
https://github.com/jczic/BLEAdvReader/blob/master/main.py

Data must became from a scan of Bluetooth advertisement data :
`bluetooth.get_adv().data`
👍

**Comment by surajrimal** [comment]
Can anyone help me to work with MQTT subscribed data? The data is in JSON format.

**Comment by jczic** [comment]
MQTT is not the subject here...
