### ISSUE TITLE
Question about adding proximity data and identifying iBeacon advs

### ISSUE THREAD

**Issue by gregsvo** [jczic/BLEAdvReader#4]
First off, _thank _you_ for this great tool. It's helped me a _lot._

I had a couple of questions for you:

Question 1: I noticed that `EddyStoneTLMUnencrypted` does not have proximity functions (`GetProximityByLogTX`/`GetProximityByOldBconTX`/`GetProximityByNewBconTX`), but `EddyStoneEID` does. Is there a reason for this? **Can those proximity functions be added to the `EddyStoneTLMUnencrypted` class?**

Question 2: I am trying to triangulate the position of a beacon based on several units detecting the iBeacon advertisement. Unfortunately I don't see unique numbers/advertisement id being passed with iBeacon advertisments. For example, `EddyStoneTLMUnencrypted` has `advCnt` and `secCnt`, so I can differentiate advertisements from each other, because of the unique number passed with each advertisement.  **Is there any unique timestamp, adv count, or other unique passed with iBeacon advertisments that I don't know of? How do you recommend I differentiate advertisements?**

Again, thanks you for your hard work, it's very helpful!

**Comment by jczic** [comment]
Hello @gregsvo,
Thank you for your interest, you are welcome :)

---

Question1:

Yes, `EddyStoneTLMUnencrypted` and `EddyStoneTLMEncrypted` do not have any native TxPower information included in advertisement messages.

---

Question2:

You perform the scan and therefore have all the data of advertisement messages.
Inside, you find the RSSI (which you use for triangulation) and then transmit each message to the bleAdvReader library to analyse and perhaps normalize messages as classes.
Be careful, "iBeacons" comes from Apple, "EddyStones" comes from Google and they are named "Beacons" (not iBeacons).

To read a unique Apple iBeacon identifier, you can use the `UUID` property of the `AppleIBeacon` class.
It is indeed the "applicative" identifier of the iBeacon and not the global identifier.

About the Google EddyStones, those that are encrypted do not publish unique information in clear.
For `EddyStoneUID` it is the properties `Namespace` and `Instance`.
For `EddyStoneURL` it is only the property `URL`.
And for `EddyStoneTLMUnencrypted` the unique identifier can only be obtained after connection with it (paired).
 (see protocol at: https://github.com/google/eddystone/blob/master/protocol-specification.md).

---

Tips:
If you want to correctly locate the beacons, you should sample multiple RSSI values and apply the correct formula to the average or the median of the set using the `ProximityHelper` class :)

**Comment by gregsvo** [comment]
Thanks for the help!
